### ISSUE TITLE
Feature request to exlude files by extension

### ISSUE THREAD

**Issue by Nogbit** [SublimeText/TrailingSpaces#63]
I would like to exclude my README.md files when saving because trailing spaces actually have meaning in markdown.

**Comment by ajmueller** [comment]
@Nogbit I just ran across this and am interested in the method to get this working.  Like @tkellen, I have files (specifically Jade templates) that need to have trailing spaces.

**Comment by HaxtonFale** [comment]
A bit of an old issue, but I'm running into the same problem, and cannot work with exclusion by syntax type.

I'm working with Salesforce files, and some of them are XMLs. I would want to disable trailing space highlight and removal in all files with the extension `.object` rather than all XML files (some contain embedded managed code and Salesforce complains if I try to push with trailing spaces removed).
